In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing as prep
from sklearn import pipeline
from sklearn import compose
from sklearn import tree

In [2]:
np.random.seed(42)
size = (15, )
c_ary = np.random.choice(a=['a', 'b', 'c'], size=size)
c2_ary = np.random.choice(a=['X', 'Y'], size=size)
n_ary = np.random.randint(0, 10, size=size)
l_ary = np.array([ord(x) for x in c_ary])
df = pd.DataFrame({'cats':c_ary, 'groups':c2_ary, 'nums':n_ary})

In [3]:
test_size = (10, )
c_ary_t = np.random.choice(a=['a', 'b', 'c'], size=test_size)
c2_ary_t = np.random.choice(a=['X', 'Y'], size=test_size)
n_ary_t = np.random.randint(0, 10, size=test_size)
l_ary_t = np.array([ord(x) for x in c_ary_t])
df_t = pd.DataFrame({'cats':c_ary_t, 'groups':c2_ary_t, 'nums':n_ary_t})

In [4]:
print(df)

   cats groups  nums
0     c      X     8
1     a      Y     0
2     c      Y     9
3     c      Y     2
4     a      Y     6
5     a      Y     3
6     c      Y     8
7     b      Y     2
8     c      Y     4
9     c      X     2
10    c      X     6
11    c      Y     4
12    a      Y     8
13    c      Y     6
14    b      X     1


In [5]:
print(df_t)

  cats groups  nums
0    a      Y     3
1    b      X     1
2    b      Y     5
3    b      X     5
4    a      X     9
5    b      Y     3
6    a      X     5
7    b      Y     1
8    c      Y     9
9    c      Y     1


In [13]:
ohe = prep.OneHotEncoder()
identity = prep.FunctionTransformer()

clf = tree.DecisionTreeClassifier()

c_transformer = pipeline.Pipeline(steps=[
    ('ohe', ohe)
])

n_transformer = pipeline.Pipeline(steps=[
    ('identity', identity)
])

transformer = compose.ColumnTransformer(transformers=[
    ('treat_c', c_transformer, ['cats', 'groups']),
    ('treat_n', n_transformer, ['nums']),
])

pipe = pipeline.Pipeline(steps=[
    ('transfomer', transformer),
    ('classifier', clf)
])

In [14]:
trans_df = pipe.fit_transform(X=df, y=l_ary)

AttributeError: 'DecisionTreeClassifier' object has no attribute 'transform'

In [8]:
print(trans_df)

[[0. 0. 1. 1. 0. 8.]
 [1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 9.]
 [0. 0. 1. 0. 1. 2.]
 [1. 0. 0. 0. 1. 6.]
 [1. 0. 0. 0. 1. 3.]
 [0. 0. 1. 0. 1. 8.]
 [0. 1. 0. 0. 1. 2.]
 [0. 0. 1. 0. 1. 4.]
 [0. 0. 1. 1. 0. 2.]
 [0. 0. 1. 1. 0. 6.]
 [0. 0. 1. 0. 1. 4.]
 [1. 0. 0. 0. 1. 8.]
 [0. 0. 1. 0. 1. 6.]
 [0. 1. 0. 1. 0. 1.]]


In [15]:
pipe.named_steps

{'transfomer': ColumnTransformer(transformers=[('treat_c',
                                  Pipeline(steps=[('ohe', OneHotEncoder())]),
                                  ['cats', 'groups']),
                                 ('treat_n',
                                  Pipeline(steps=[('identity',
                                                   FunctionTransformer())]),
                                  ['nums'])]),
 'classifier': DecisionTreeClassifier()}

In [66]:
trans_df.score(X=df_t, y=l_ary_t)

1.0

In [68]:
trans_df_t = pipe.predict(df_t)

In [79]:
pipe.predict(pd.DataFrame({'cats':['b'], 'nums':[None]}))

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [69]:
trans_df_t

array([98, 98, 98, 98, 98, 98, 97, 99, 98, 98])

In [ ]:
ary_t = ohe_f.transform(ary)

In [ ]:
print(ary_t)

In [15]:
d1 = {'a':1, 'b':2}
d2 = {'c':3, 'd':4}

In [18]:
ds = {**d1, **d2}

In [19]:
ds

{'a': 1, 'b': 2, 'c': 3, 'd': 4}